### ISSUE TITLE
ss_netsnmp_memory_syntax parameter order wrong

### ISSUE THREAD

**Issue by fanto666** [netniV/cacti-netsnmp-memory#3]
the ss_netsnmp_memory_syntax function reports incorrect order of parameters:

        print "Syntax: ss_netsnmp_memory.php <hostname> <snmp_version> <snmp_community>\ \n" .
        "      [<snmp3_username> <snmp3_password> <snmp3_auth_protocol> <snmp3_priv_password>\ \n" .
        "      [<snmp3_priv_protocol> <snmp3_context> <snmp_port>} <snmp_timeout> \n";

port and timeout should immediately follow snmp community, not be at the end.

**Comment by netniV** [comment]
Thanks @fanto666 - I have updated this now.
