### ISSUE TITLE
cacti_snmp_get expects timeout in milliseconds, but script passes microseconds

### ISSUE THREAD

**Issue by nuno-silva** [netniV/cacti-netsnmp-memory#7]
`cacti_snmp_get` expects timeout to be in milliseconds:

https://github.com/Cacti/cacti/blob/6ffea1fe1ef7fd500af5c14220521845fb2d5998/lib/snmp.php#L117-L121

but `ss_netsnmp_memory.php` is passing the timeout value in microseconds.

This results in very high timeouts of several thousand seconds instead of just a few seconds.

I'm preparing a pull request to fix this.

**Comment by netniV** [comment]
Change looks good, so I'll add it in.
