### ISSUE TITLE
getting usedReal greater than memTotalReal

### ISSUE THREAD

**Issue by nuno-silva** [netniV/cacti-netsnmp-memory#9]
`usedReal` is getting bigger than `memTotalReal`, even with little swap usage:

![current_b](https://user-images.githubusercontent.com/6935057/80660986-44562080-8a85-11ea-9d99-6f3b268a036a.png)
![current_0](https://user-images.githubusercontent.com/6935057/80660990-45874d80-8a85-11ea-9024-c730408792fd.png)

Reverting #6 seems to fix it, so there may be a problem with it:

![reverted_b](https://user-images.githubusercontent.com/6935057/80661001-50da7900-8a85-11ea-9cb1-5d5cd39782dd.png)
![reverted_0](https://user-images.githubusercontent.com/6935057/80661008-52a43c80-8a85-11ea-937e-c2ead4f19862.png)

Here's some example data from my RPi Zero device:
```
.1.3.6.1.2.1.25.2.2.0  HOST-RESOURCES-MIB::hrMemorySize.0 = INTEGER: 443076 KBytes
.1.3.6.1.4.1.2021.4.5.0  UCD-SNMP-MIB::memTotalReal.0 = INTEGER: 443076 kB
.1.3.6.1.4.1.2021.4.6.0  UCD-SNMP-MIB::memAvailReal.0 = INTEGER: 29188 kB
.1.3.6.1.4.1.2021.4.3.0  UCD-SNMP-MIB::memTotalSwap.0 = INTEGER: 102396 kB
.1.3.6.1.4.1.2021.4.4.0  UCD-SNMP-MIB::memAvailSwap.0 = INTEGER: 98812 kB
.1.3.6.1.4.1.2021.4.14.0  UCD-SNMP-MIB::memBuffer.0 = INTEGER: 42620 kB
.1.3.6.1.4.1.2021.4.15.0  UCD-SNMP-MIB::memCached.0 = INTEGER: 302084 kB
```
```
root@zero:~# cat /proc/meminfo | grep -E "Mem|Swap[TF]|^Cache|Buff"
MemTotal:         443076 kB
MemFree:           29140 kB
MemAvailable:     318788 kB
Buffers:           42620 kB
Cached:           302084 kB
SwapTotal:        102396 kB
SwapFree:          98812 kB
```

Note that the new OID for `totalReal` used in #6 gives me exactly the same result, so the issue must be in the [new](https://github.com/netniV/cacti-netsnmp-memory/pull/6/files#diff-b496ea2c7b8bf32171821b850959c5b5L120-R121) computation of `usedReal`:

https://github.com/netniV/cacti-netsnmp-memory/blob/f00431317331ee3bb03a961b1050baca311f4716/scripts/ss_netsnmp_memory.php#L116-L117

Indeed, `(443 076 - (29188 - 42620 - 302084)) = 758592`, which is greater than my 443076 KB of RAM.

Contrary to https://github.com/netniV/cacti-netsnmp-memory/pull/6#issue-385059158, my `availReal` is **not** the result of `/proc/meminfo` `MemAvailable + buffer + cache`: 29188 != `318788+42620+302084 = 663492`.
Rather, `memAvailReal` seems to be meminfo's `MemFree`, so the old computation seems just fine.

**Comment by nuno-silva** [comment]
@gjimenezf can you perhaps try increasing the memory usage on one of your servers and see if this happens to you?

**Comment by nuno-silva** [comment]
Here's an example from another cacti instance:

![hive](https://user-images.githubusercontent.com/6935057/80666026-02cc7200-8a93-11ea-8fff-598d77ad8c2c.png)

- At ~02:37 I allocated 20GB of RAM.
- At ~02:48 I allocated 20 more GB of RAM.
- At ~3:00 I started increasing the amount of buffers by reading a really big file. You can see it makes the graph go further above `memTotalReal`, so it's clear that at least "buffers" are being stacked/summed twice in the graph: once by `memBuffer` and then again in the (wrong) computation of `usedReal`. Cache too, even though I did not test that.

- At ~3:18, I reverted #6. After this, the graph starts to look more like the memory usage reported by htop (green is used, blue is buffers, yellow is cache, gray is free):

![hive htop at 3:24](https://user-images.githubusercontent.com/6935057/80665676-0ca1a580-8a92-11ea-8189-2d5fc78fbe70.png)

**Comment by netniV** [comment]
So does this mean #6 needs reverting?

**Comment by nuno-silva** [comment]
Yes, at least partially. I would wait for @gjimenezf's input though. Maybe he's running some shiny new kernel or snmpd that changed way the values are reported and if that's the case more changes are needed.

**Comment by netniV** [comment]
We have had no feedback from @gjimenezf so, I guess its our call @nuno-silva?

**Comment by nuno-silva** [comment]
Yes, please revert #6.

Both `UCD-SNMP-MIB::memTotalReal.0` (`.1.3.6.1.4.1.2021.4.5.0`) and `HOST-RESOURCES-MIB::hrMemorySize.0` (`.1.3.6.1.2.1.25.2.2.0`) OIDs give the same value on all my host, so I think you can keep using memTotalReal for consistency with the other ones and only revert the bad calculations.

**Comment by netniV** [comment]
I have now reverted c3feb030e865c3da1ec0f76bdf5b3f84d1a2a3ec so that 29a27a0 should show as expected.  Unless you also want memCached deleting not adding? But that seems to be the bug with his change.

**Comment by nuno-silva** [comment]
29a27a0 looks good. Thanks!
